cd C:\Users\Alex\Desktop\Atlas

.\scripts\run-atlas.ps1 -TenantPath ".\tenants\example_tenant.json" -OnlyControls "DisableUserConsentToApps,GuestInvitesRestrictedToAdminsAndGuestInviters,EmailVerifiedUsersCannotJoinOrganization,EmailBasedSubscriptionsDisabled,BlockMsolPowerShellEnabled,DefaultUserRoleAppsCreationDisabled,DefaultUserRoleSecurityGroupsCreationDisabled,DefaultUserRoleTenantCreationDisabled,DefaultUserRoleReadOtherUsersDisabled,DefaultUserRoleReadBitlockerKeysForOwnedDeviceDisabled,ThirdPartyAppsRestricted,AdminOwnedAppsRestricted,IntegratedAppsRestricted"
