cd C:\Users\Alex\Desktop\Atlas

.\scripts\run-atlas.ps1 -TenantPath ".\tenants\example_tenant.json" -OnlyControls `
"SharePointDefaultSharingRestricted,SharePointLinkExpirationConfigured,SharePointDefaultLinkTypeRestricted,SharePointDomainRestrictionConfigured,SharePointSharingAllowedDomainListConfigured,SharePointPreventExternalUsersFromResharingEnabled"
